#!/bin/bash

CONSTRAINT_URL=https://raw.githubusercontent.com/apache/airflow/constraints-$AIRFLOW_VERSION/constraints-$PYTHON_VERSION.txt

pip install "apache-airflow==$AIRFLOW_VERSION" --constraint $CONSTRAINT_URL
pip install "psycopg2-binary==2.9.6"
pip install "apache-airflow-providers-mongo==2.3.1"
pip freeze > requirements.txt