#!/bin/bash

export MONGO_USERNAME=admin
export MONGO_PASSWORD=admin
export MONGO_HOST=mongo
export MONGO_PORT=27017
export MONGO_DATABASE=
export AIRFLOW_MONGO_CONNECTION_ID=mongo_bbb

docker exec -it airflow_scheduler bash -c " \
    airflow connections add \
        --conn-uri "mongo://$MONGO_USERNAME:$MONGO_PASSWORD@$MONGO_HOST:$MONGO_PORT/$MONGO_DATABASE" \
        $AIRFLOW_MONGO_CONNECTION_ID \
"